spring:
  application:
    name: crud-springboot

  datasource:
    url: jdbc:postgresql://localhost:5432/crud_springboot
    username: postgres
    password: Admin@1621
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect